POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "username": "hussein2",
    "email": "hussein2@yahoo.com",
    "password": "password"
}

###

POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "hussein@yahoo.com",
    "password": "password"
}

###

GET http://localhost:3000/api/todo
Content-Type: application/json
Authorization: Bearer $TOKEN


###

POST http://localhost:3000/api/todo
Content-Type: application/json
Authorization: Bearer $TOKEN

{
    "title": "todo3",
    "body": "third todo created using rest"
}

###

POST http://localhost:3000/api/todo
Content-Type: application/json
Authorization: Bearer $TOKEN

{
    "title": "todo2",
    "body": "second todo created using rest"
}

###


POST http://localhost:3000/api/todo
Content-Type: application/json
Authorization: Bearer $TOKEN

{
    "title": "todo2",
    "body": "second todo created using rest"
}
